# Development Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV NODE_OPTIONS=--max-old-space-size=3072
RUN npm run prisma:generate
RUN npm run build
CMD ["npm", "run", "start:dev"]
